image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

pages:
  stage: deploy
  script:
  - npm build
  - mkdir .public
  - cp -r /dist .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
